CREATE DATABASE TOUCH_MUSIC

CREATE TABLE USERS(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AUDIOS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT, 
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  size INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE TRANSCRIPTIONS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  audio_id INT,
  transcription TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (audio_id) REFERENCES audios(id)
);

CREATE TABLE SONGS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  audio_id INT,
  title VARCHAR(255),
  chords TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (audio_id) REFERENCES audios(id)
);
